name: CI

on: push

jobs:
    code:
        runs-on: ubuntu-latest

        steps:
            - name: Check code
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: yarn install
            - name: Check code with ESLint
              run: yarn lint
        #   - name: Run tests
        #     run: yarn test

    build:
        needs: code
        runs-on: ubuntu-latest

        steps:
            - name: Check code
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: yarn install
            - name: Build
              run: yarn build
